identifier   = "org.workspace"
product-name = "workspace"
version      = "0.1.0"


[[app.windows]]
title = "workspace"

height = 600
width  = 800


[build]
before-build-command = "pnpm build"
before-dev-command   = "pnpm --filter webview dev"
dev-url              = "http://localhost:1420"
frontend-dist        = "../../packages/webview/dist"


[bundle]
active  = true
icon    = ["icons/128x128.png", "icons/128x128@2x.png", "icons/32x32.png", "icons/icon.icns", "icons/icon.ico"]
targets = "all"
