[env]
RPC_PROTO_DIR = { value = "proto", relative = true }

RUST_LOG = 'trace'

# MIMALLOC_SHOW_STATS = '1'
# MIMALLOC_VERBOSE    = '1'


# [target.x86_64-unknown-linux-gnu]
# linker    = "clang"
# rustflags = ["-Clink-arg=-Wl,--no-rosegment", "-Clink-arg=-fuse-ld=lld"]
